INSERT INTO Employee (EMPLOYEE_ID, FIRST_NAME,LAST_NAME,EMPLOYEE_ROLE,SALARY) VALUES ('1','Camilo','Castano','Administrador',10000000);
INSERT INTO Employee (EMPLOYEE_ID, FIRST_NAME,LAST_NAME,EMPLOYEE_ROLE,SALARY) VALUES ('2','Josue','Hernandez','Grente de Poryectos',10000000);
INSERT INTO Employee (EMPLOYEE_ID, FIRST_NAME,LAST_NAME,EMPLOYEE_ROLE,SALARY) VALUES ('3','Saray','Gonzales','Ingeniera de Sistemas',10000000.5);

